services:
  mongo:
    image: mongo:7
    container_name: finance-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-api
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: 
      JWT_SECRET: 12313
      JWT_EXPIRES_IN: 1d
      REFRESH_JWT_SECRET: 1323213
      REFRESH_JWT_EXPIRES_IN: 7d

volumes:
  mongo_data:
